services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis on port 6379
    volumes:
      - redis-data:/data # Persist Redis data

volumes:
  redis-data:
