require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dns_zones", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DnsZone. As you add validations to DnsZone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DnsZone.create! valid_attributes
      get dns_zones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dns_zone = DnsZone.create! valid_attributes
      get dns_zone_url(dns_zone)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dns_zone_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      dns_zone = DnsZone.create! valid_attributes
      get edit_dns_zone_url(dns_zone)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DnsZone" do
        expect {
          post dns_zones_url, params: { dns_zone: valid_attributes }
        }.to change(DnsZone, :count).by(1)
      end

      it "redirects to the created dns_zone" do
        post dns_zones_url, params: { dns_zone: valid_attributes }
        expect(response).to redirect_to(dns_zone_url(DnsZone.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DnsZone" do
        expect {
          post dns_zones_url, params: { dns_zone: invalid_attributes }
        }.to change(DnsZone, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post dns_zones_url, params: { dns_zone: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dns_zone" do
        dns_zone = DnsZone.create! valid_attributes
        patch dns_zone_url(dns_zone), params: { dns_zone: new_attributes }
        dns_zone.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dns_zone" do
        dns_zone = DnsZone.create! valid_attributes
        patch dns_zone_url(dns_zone), params: { dns_zone: new_attributes }
        dns_zone.reload
        expect(response).to redirect_to(dns_zone_url(dns_zone))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        dns_zone = DnsZone.create! valid_attributes
        patch dns_zone_url(dns_zone), params: { dns_zone: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dns_zone" do
      dns_zone = DnsZone.create! valid_attributes
      expect {
        delete dns_zone_url(dns_zone)
      }.to change(DnsZone, :count).by(-1)
    end

    it "redirects to the dns_zones list" do
      dns_zone = DnsZone.create! valid_attributes
      delete dns_zone_url(dns_zone)
      expect(response).to redirect_to(dns_zones_url)
    end
  end
end
