---
- name: Provision and deploy CoreDNS with Redis plugin
  hosts: all
  become: yes
  vars:
    coredns_version: "v1.12.0"
    go_version: "1.23.6"
    # deploy_user, deploy_password, redis_host are passed via --extra-vars
    home_path: "/home/{{ deploy_user }}"
    coredns_src: "{{ home_path }}/coredns"

  tasks:
    # ----------------------------------------------------------------
    # 1. Create deploy user
    # ----------------------------------------------------------------
    - name: Create deploy user
      ansible.builtin.user:
        name: "{{ deploy_user }}"
        shell: /bin/bash
        create_home: yes
        password: "{{ deploy_password | password_hash('sha512') }}"
        groups: sudo
        append: yes

    - name: Grant passwordless sudo to deploy user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ deploy_user }}"
        content: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL\n"
        mode: "0440"
        validate: "visudo -cf %s"

    # ----------------------------------------------------------------
    # 2. Install system packages
    # ----------------------------------------------------------------
    - name: Update, upgrade, and install system dependencies
      ansible.builtin.shell: |
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
          git make build-essential ca-certificates wget curl ufw
      changed_when: true

    # ----------------------------------------------------------------
    # 3. Install Go (conditional)
    # ----------------------------------------------------------------
    - name: Check if Go {{ go_version }} is installed
      ansible.builtin.command: /usr/local/go/bin/go version
      register: go_check
      changed_when: false
      failed_when: false

    - name: Install Go {{ go_version }}
      when: go_check.rc != 0 or go_version not in (go_check.stdout | default(''))
      ansible.builtin.shell: |
        rm -rf /usr/local/go
        wget -qO- "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz" | tar -C /usr/local -xzf -
      changed_when: true

    - name: Add Go to deploy user's PATH in .bashrc
      ansible.builtin.blockinfile:
        path: "{{ home_path }}/.bashrc"
        marker: "# {mark} GO CONFIG"
        block: |
          export PATH="$PATH:/usr/local/go/bin"
        owner: "{{ deploy_user }}"

    # ----------------------------------------------------------------
    # 4. Disable systemd-resolved (frees port 53 on Ubuntu)
    # ----------------------------------------------------------------
    - name: Stop and disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
      ignore_errors: yes

    - name: Configure resolv.conf for direct DNS
      ansible.builtin.shell: |
        sed -i '/nameserver 127.0.0.53/d' /etc/resolv.conf
        grep -q 'nameserver 8.8.8.8' /etc/resolv.conf || echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
      changed_when: true

    # ----------------------------------------------------------------
    # 5. Clone or update CoreDNS source
    # ----------------------------------------------------------------
    - name: Clone or update CoreDNS {{ coredns_version }}
      ansible.builtin.git:
        repo: "https://github.com/coredns/coredns.git"
        dest: "{{ coredns_src }}"
        version: "{{ coredns_version }}"
        force: yes
        accept_hostkey: yes
      become_user: "{{ deploy_user }}"

    # ----------------------------------------------------------------
    # 6. Add Redis plugin and compile
    # ----------------------------------------------------------------
    - name: Add Redis plugin to plugin.cfg
      ansible.builtin.lineinfile:
        path: "{{ coredns_src }}/plugin.cfg"
        insertafter: "^cache:cache"
        line: "redis:github.com/codysnider/coredns-redis"

    - name: Compile CoreDNS with Redis plugin
      community.general.make:
        chdir: "{{ coredns_src }}"
      become_user: "{{ deploy_user }}"
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_facts['env']['PATH'] }}"
        HOME: "{{ home_path }}"

    # ----------------------------------------------------------------
    # 7. Deploy Corefile and systemd service
    # ----------------------------------------------------------------
    - name: Create /etc/coredns directory
      ansible.builtin.file:
        path: /etc/coredns
        state: directory
        mode: "0755"

    - name: Deploy Corefile
      ansible.builtin.copy:
        dest: /etc/coredns/Corefile
        content: |
          . {
          	log
                  health :8053
                  errors
                  reload
          	redis {
          		address {{ redis_host }}:6379
          		ttl 10
          		connect_timeout 200
          		read_timeout 200
          	}
          	cache 30
          }
        mode: "0644"
      notify: Restart CoreDNS

    - name: Deploy CoreDNS systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/coredns.service
        content: |
          [Unit]
          Description=CoreDNS DNS Server
          Documentation=https://coredns.io/manual/toc/
          After=network.target

          [Service]
          User={{ deploy_user }}
          Group={{ deploy_user }}
          CapabilityBoundingSet=CAP_NET_BIND_SERVICE
          AmbientCapabilities=CAP_NET_BIND_SERVICE
          NoNewPrivileges=true
          WorkingDirectory=/etc/coredns
          ExecStart={{ coredns_src }}/coredns -conf /etc/coredns/Corefile
          Restart=on-failure
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
        mode: "0644"
      notify: Restart CoreDNS

    # ----------------------------------------------------------------
    # 8. Configure UFW firewall and start services
    # ----------------------------------------------------------------
    - name: Configure UFW rules and enable
      ansible.builtin.shell: |
        ufw allow 22/tcp
        ufw allow 443/tcp
        ufw allow 53/tcp
        ufw allow 53/udp
        ufw default deny incoming
        ufw default allow outgoing
        ufw --force enable
      changed_when: true

    - name: Enable and start CoreDNS
      ansible.builtin.systemd:
        name: coredns
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Restart CoreDNS
      ansible.builtin.systemd:
        name: coredns
        state: restarted
        daemon_reload: yes
