---
- name: Install packages and gems on localhost
  hosts: localhost
  become: yes # Use sudo to become the root user

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - autoconf
          - bison
          - bison
          - build-essential
          - curl
          - git
          - inotify-tools
          - libffi-dev
          - libgdbm-dev
          - libncur
          - libncurses5-dev
          - libpq-dev
          - libreadline-dev
          - libreadline-dev
          - libssl-dev
          - libssl-dev
          - libvips
          - libyaml-dev
          - net-tools
          - net-tools
          - openssh-server
          - pkg-config
          - screen
          - wireguard
          - zlib1g-dev

        state: present
        update_cache: yes
