---
- name: Provision and deploy CoreDNS UI
  hosts: all
  become: yes
  vars:
    app_name: "coredns_ui"
    # deploy_user, deploy_password, puma_port are passed via --extra-vars
    home_path: "/home/{{ deploy_user }}"
    app_path: "{{ home_path }}/{{ app_name }}"
    ruby_version: "4.0.1"
    ruby_major_minor: "4.0"
    node_version: "24.13.1"
    nvm_version: "0.40.4"
    gem_home: "{{ home_path }}/.ruby"
    ruby_env:
      GEM_HOME: "{{ gem_home }}"
      PATH: "{{ gem_home }}/bin:/usr/local/bin:{{ ansible_facts['env']['PATH'] }}"

  tasks:
    # ----------------------------------------------------------------
    # 1. Create deploy user
    # ----------------------------------------------------------------
    - name: Create deploy user
      ansible.builtin.user:
        name: "{{ deploy_user }}"
        shell: /bin/bash
        create_home: yes
        password: "{{ deploy_password | password_hash('sha512') }}"
        groups: sudo
        append: yes

    - name: Grant passwordless sudo to deploy user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ deploy_user }}"
        content: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL\n"
        mode: "0440"
        validate: "visudo -cf %s"

    # ----------------------------------------------------------------
    # 2. Install system packages
    # ----------------------------------------------------------------
    - name: Update, upgrade, and install system dependencies
      ansible.builtin.shell: |
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
          ca-certificates curl wget rsync git build-essential pkg-config \
          libssl-dev libreadline-dev zlib1g-dev libffi-dev libffi8 \
          libyaml-dev libpq-dev libsqlite3-dev libvips openssh-server \
          net-tools redis-server redis-tools
      changed_when: true

    # ----------------------------------------------------------------
    # 3. Install Rust (needed for Ruby YJIT)
    # ----------------------------------------------------------------
    - name: Install Rust if missing and set stable toolchain
      ansible.builtin.shell: |
        if ! {{ home_path }}/.cargo/bin/rustc --version > /dev/null 2>&1; then
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        fi
        {{ home_path }}/.cargo/bin/rustup default stable
      become_user: "{{ deploy_user }}"
      changed_when: true

    # ----------------------------------------------------------------
    # 4. Install Ruby from source
    # ----------------------------------------------------------------
    - name: Check if Ruby {{ ruby_version }} is installed
      ansible.builtin.command: /usr/local/bin/ruby -v
      register: ruby_check
      changed_when: false
      failed_when: false

    - name: Install Ruby {{ ruby_version }} from source
      when: ruby_check.rc != 0 or ruby_version not in (ruby_check.stdout | default(''))
      block:
        - name: Download Ruby {{ ruby_version }}
          ansible.builtin.get_url:
            url: "https://cache.ruby-lang.org/pub/ruby/{{ ruby_major_minor }}/ruby-{{ ruby_version }}.tar.gz"
            dest: "/tmp/ruby-{{ ruby_version }}.tar.gz"

        - name: Extract Ruby source
          ansible.builtin.unarchive:
            src: "/tmp/ruby-{{ ruby_version }}.tar.gz"
            dest: /tmp
            remote_src: yes

        - name: Configure Ruby
          ansible.builtin.command:
            cmd: ./configure --disable-install-rdoc --enable-yjit
            chdir: "/tmp/ruby-{{ ruby_version }}"
          environment:
            PATH: "{{ home_path }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"

        - name: Build Ruby
          community.general.make:
            chdir: "/tmp/ruby-{{ ruby_version }}"
          environment:
            PATH: "{{ home_path }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"

        - name: Install Ruby
          community.general.make:
            chdir: "/tmp/ruby-{{ ruby_version }}"
            target: install
          environment:
            PATH: "{{ home_path }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"

        - name: Clean up Ruby source
          ansible.builtin.shell: rm -rf "/tmp/ruby-{{ ruby_version }}.tar.gz" "/tmp/ruby-{{ ruby_version }}"
          changed_when: true

    # ----------------------------------------------------------------
    # 5. Configure GEM_HOME for deploy user
    # ----------------------------------------------------------------
    - name: Set GEM_HOME and PATH in .bashrc
      ansible.builtin.blockinfile:
        path: "{{ home_path }}/.bashrc"
        marker: "# {mark} RUBY GEM CONFIG"
        block: |
          export GEM_HOME=~/.ruby/
          export PATH="$PATH:~/.ruby/bin"
        owner: "{{ deploy_user }}"

    # ----------------------------------------------------------------
    # 6. Install NVM, Node.js, and Yarn
    # ----------------------------------------------------------------
    - name: Check if NVM is installed
      ansible.builtin.stat:
        path: "{{ home_path }}/.nvm/nvm.sh"
      register: nvm_stat

    - name: Install NVM
      ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
      become_user: "{{ deploy_user }}"
      when: not nvm_stat.stat.exists

    - name: Install Node.js {{ node_version }} and Yarn
      ansible.builtin.shell: |
        export NVM_DIR="{{ home_path }}/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm install {{ node_version }}
        npm install yarn -g
      become_user: "{{ deploy_user }}"
      args:
        executable: /bin/bash

    # ----------------------------------------------------------------
    # 7. Backup and clone application
    # ----------------------------------------------------------------
    - name: Backup and rotate old releases
      ansible.builtin.shell: |
        if [ -d "{{ app_path }}" ] && [ "$(ls -A {{ app_path }})" ]; then
          for i in 4 3 2 1; do
            src="{{ app_path }}.bak.${i}"
            dst="{{ app_path }}.bak.$((i+1))"
            [ -d "$src" ] && mv "$src" "$dst"
          done
          rm -rf "{{ app_path }}.bak.5" "{{ app_path }}.bak.1"
          mv "{{ app_path }}" "{{ app_path }}.bak.1"
        else
          rm -rf "{{ app_path }}"
        fi
      changed_when: true

    - name: Clone coredns_ui repository
      ansible.builtin.git:
        repo: "https://github.com/ajeygore/coredns_ui.git"
        dest: "{{ app_path }}"
        version: main
        accept_hostkey: yes
      become_user: "{{ deploy_user }}"

    - name: Ensure deploy user owns application directory
      ansible.builtin.file:
        path: "{{ app_path }}"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        recurse: yes

    # ----------------------------------------------------------------
    # 8. Install gems, deploy env, precompile assets
    # ----------------------------------------------------------------
    - name: Install Bundler gem
      community.general.gem:
        name: bundler
        state: present
      environment: "{{ ruby_env }}"

    - name: Configure bundle path and install gems
      ansible.builtin.shell: |
        bundle config set --local path {{ home_path }}/.bundledgems
        bundle install --jobs 4 --retry 3
      args:
        chdir: "{{ app_path }}"
        executable: /bin/bash
      become_user: "{{ deploy_user }}"
      environment: "{{ ruby_env }}"

    - name: Copy .env file to app directory
      ansible.builtin.copy:
        src: "{{ env_file }}"
        dest: "{{ app_path }}/.env"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0600"

    # ----------------------------------------------------------------
    # 9. SECRET_KEY_BASE
    # ----------------------------------------------------------------
    - name: Check if persistent SECRET_KEY_BASE file exists
      ansible.builtin.stat:
        path: "{{ home_path }}/.secret_key_base"
      register: secret_key_file

    - name: Generate persistent SECRET_KEY_BASE file
      ansible.builtin.shell: |
        openssl rand -hex 64 > {{ home_path }}/.secret_key_base
        chmod 0600 {{ home_path }}/.secret_key_base
        chown {{ deploy_user }}:{{ deploy_user }} {{ home_path }}/.secret_key_base
      when: not secret_key_file.stat.exists

    - name: Read SECRET_KEY_BASE from persistent file
      ansible.builtin.command: cat {{ home_path }}/.secret_key_base
      register: secret_key_base_raw
      changed_when: false

    - name: Set SECRET_KEY_BASE fact
      ansible.builtin.set_fact:
        secret_key_base: "{{ secret_key_base_raw.stdout | trim }}"

    # ----------------------------------------------------------------
    # 10. Database setup and asset precompilation
    # ----------------------------------------------------------------
    - name: Create production database directory
      ansible.builtin.file:
        path: "{{ home_path }}/coredns-app-db"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0755"

    - name: Run database migrations
      ansible.builtin.command:
        cmd: bundle exec rails db:migrate
        chdir: "{{ app_path }}"
      become_user: "{{ deploy_user }}"
      environment:
        RAILS_ENV: production
        SECRET_KEY_BASE: "{{ secret_key_base }}"
        GEM_HOME: "{{ gem_home }}"
        PATH: "{{ gem_home }}/bin:/usr/local/bin:{{ ansible_facts['env']['PATH'] }}"

    - name: Precompile assets
      ansible.builtin.command:
        cmd: bundle exec rails assets:precompile
        chdir: "{{ app_path }}"
      become_user: "{{ deploy_user }}"
      environment:
        RAILS_ENV: production
        SECRET_KEY_BASE: "{{ secret_key_base }}"
        GEM_HOME: "{{ gem_home }}"
        PATH: "{{ gem_home }}/bin:/usr/local/bin:{{ ansible_facts['env']['PATH'] }}"

    # ----------------------------------------------------------------
    # 11. Create systemd service
    # ----------------------------------------------------------------
    - name: Create systemd service for Puma
      ansible.builtin.copy:
        dest: /etc/systemd/system/coredns_ui.service
        content: |
          [Unit]
          Description=Puma HTTP Server for CoreDNS UI
          After=network.target redis-server.service

          [Service]
          Type=simple
          User={{ deploy_user }}
          WorkingDirectory={{ app_path }}
          ExecStart=/usr/local/bin/bundle exec puma -C {{ app_path }}/config/puma.rb
          Restart=always
          EnvironmentFile={{ app_path }}/.env
          Environment=SECRET_KEY_BASE={{ secret_key_base }}
          Environment=RAILS_ENV=production
          Environment=GEM_HOME={{ gem_home }}
          Environment=PATH={{ gem_home }}/bin:/usr/local/bin:/usr/bin:/bin

          [Install]
          WantedBy=multi-user.target
      notify: Restart Puma

    - name: Enable and start Puma
      ansible.builtin.systemd:
        name: coredns_ui
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Restart Puma
      ansible.builtin.systemd:
        name: coredns_ui
        state: restarted
        daemon_reload: yes
